import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

import { GlobalReduxProvider } from "./globalRedux/provider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: "Z_LGEKdrhWWjp5z7tWezFgDXJZCCPLAvC9nWAB8PnKQ",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalReduxProvider>{children}</GlobalReduxProvider>
      </body>
    </html>
  )
}
